### ISSUE TITLE
Error in Devise::SessionsController#new when activating devise_remote_client gem.

### ISSUE THREAD

**Issue by JoostVanAverbeke** [glyph-fr/devise_remote_client#1]
Good morning,
First of all thank you for your gem.

I am trying to get the devise_remote_client working in a rails 4.0.4 environment using devise 3.4.1.
I have followed the devise Getting Started Guide, and when I activate the option

 devise :database_authenticatable in my User model then my app is working as expected.

But when I change my user model to
class User
  include ActiveModel::Validations #required because some before_validations are defined in devise
  extend ActiveModel::Callbacks #required to define callbacks
  extend Devise::Models

  define_model_callbacks :validation #required by Devise

  devise :remote_authenticatable

  attr_accessor :id, :authentication_token
end

and add the following to the config/initializers/devise.rb
  config.remote_authenticatable.authentication_method do |authentication_hash|
    puts "remote_authenticatable email = #{authentication_hash[:email]} and password = #{authentication_hash[:password]}}"
  end

(I have just added the puts to the authentication_method for debugging purpose)

I get the following error:
Processing by Devise::SessionsController#new as HTML
Completed 500 Internal Server Error in 25ms

ArgumentError (wrong number of arguments(1 for 0)):
  devise (3.4.1) app/controllers/devise/sessions_controller.rb:9:in `initialize'
  devise (3.4.1) app/controllers/devise/sessions_controller.rb:9:in`new'
  devise (3.4.1) app/controllers/devise/sessions_controller.rb:9:in `new'

Do you have a idea or could you give me a direction where to start looking to fix the error?

Thanks in advance

Regards,

Joost Van Averbeke

**Comment by vala** [comment]
Hi @JoostVanAverbeke,

The errors seems to be due to the fact that your model does not define any argument inside its constructor method, since you have not declared the `initialize` method.

This is undocumented here, but I'll fix that as soon as I can.

I can think of 2 solutions. The first is to define the `initilaize` method in your user class, which should accept one argument, being an attributes hash, juste like `ActiveRecord::Base` subclasses normally do.

The second is to include `ActiveModel::Model` instead of `ActiveModel::Validations` which defines the constructor method as required. You can find ActiveModel's implementation here : https://github.com/rails/rails/blob/master/activemodel/lib/active_model/model.rb#L79-L83 

The first solution is the better if you just need this method, but I think it'll be useful to you to inherit from the other `ActiveModel::Model` modules, for your forms, translations etc.

I'll let you choose which one fits you better.

Please close the issue if it fixes your issue, but don't mind to open another one if there's any other bug.

**Comment by JoostVanAverbeke** [comment]
Good afternoon,
Sorry I didn't react any sooner. But a took a few days off.
I have tested your proposed solution and it works like a swiss watch.

Thanks a lot Valentin and have a nice weekend
